export const types = {
    CARGAR_DATA : "CARGAR_DATA",
    AGREGAR_NOTA: "AGREGAR_NOTA",
    MARCAR_NOTA: "MARCAR_NOTA",
    ELIMINAR_NOTA: "ELIMINAR_NOTA",
    LIMPIAR_COMPLETADO: "LIMPIAR_COMPLETADO"

}